namespace Ase
{
    public static class Global
    {
        /// <summary>
        /// 初始加载配置文件列表
        /// </summary>
        public static readonly string[] DataTableNames = new string[]
        {
	        //外围表
	        "ViewConfig",
	        "AccountGrade",
	        "Hero",
            "HeroSKillInfo",
            "HeroTalentBig",
            "HeroTalentSmall",
            "HeroSKillConfig", // 每个技能的详细配置
            "HeroPassive",
            "ConstantConfig",
            "EnergyConfig",
            "HeroInfo",
            //"UIHeroSkill",
            "HeroStar",
            "HeroStarRing",
            "HeroLabel",
            "HeroSeat",
            "HeroGrade",
            "Prop",
            "Entry",
            "EntryCoordinates",
            "Equipment",
            "EquipmentRank",
            "EntryStore",
            "AttributeStore",
            "Regular",
            "EquipGrade",
            "Weapon",
            "WeaponStar",
            "WeaponGrade",
            "Audio",
            "AudioAsset",
            "Voice",
            "Trust",
            
            "RandomName",
            "MapItemPreloadConfig",
            "WorldMap",
            "SectionMap",
            "Map",
            "TransferPoint",
            "CopyPoint",
            "Cavern",
            "CavernPoint",
            "MapExplore",
            "WeaponCasting",
            "EquipmentCasting",
            "HeroPropertyConvert",
            //活动
            "ActivityTask",
            "ActivityType",
            "ActivityTaskReward",
            "ActivityRank",
            "ActivityRankTask",
            "ActivityRankProgress",
            "ActivitySign",
            "ActivityTry",
            "ActivityCopy",
            "ActivityDisplay",
            
            "TeamSet",
            "PresetHeroData",
            "Question",
            "AttributeTotal",
            "Title",
            "HeadDecorate",
            "ErrorCode",
            "ReportType",
            "ReportContent",
            //副本
            "CopyMain",
            "CopyType",
            "Copy",
            "CopyDrop",
            "Permit",
            "PermitTask",
            "DropMaterial",
			"CopyStar",
			"StarConditionList",
			"RankReward",
			"Rank",
			"RankType",
			"RankUIType",
			"StarCondition",
			"DepthsStar",
			"ScoreReward",
			"CopyScore",
			"DungeonTask",
			
			"ExchangeShop",
            "ExchangeShopList",
            "MainShopList",
            "PopupTip",
            "PopupTipQueue",
            "PopupIcon",
            "Level",
            "DropGroups",
            "GoodsGroup",
            "Pay",
            
            "BoardSpine",
            "BoardHero",
            "BoardHeroList",
            "BoardBackGround",
            "SystemOpen",
            "HeroFile",
            "ScreenSettings",
			"SettingValueEnum",
			"LoadingTips",
			"Affix",
			"DamageStatistic",
			"GuidanceLevel",
			"BattlePropMake",
			"BattlePropInfo",
			"BattlePropDrawing",
			"CultivateSkillLevel",
			"CultivateSkillEffect",
			
			"PropertyKeyName",
			"Bubble",
			"BubbleQueue",
			"BattleTimeline",

			//其他
			"WarningIndicator",
			"Effect",
			"Monster",
			"MonsterAttr",
			"WorldLevel",
			"Paradox",
			"SkillTimeLine",
			"State",
			"AbnormalState",
			"WeaknessUIData",
			"WeaknessData",
			"DamageText",
			"Buff",
			"BuffStateConfig",
			"EntityHitConfig",
			"Bullet",
			"MonsterAttack", // 小怪攻击申请
			"MonsterPreloadConfig",
			"NPC",
			"SummonedEntityConfig",
			"MapItem",
			"MapItemType",
			"Task",
			"DailyTask",
			"MonsterTask",
			"BattleEntityConfig",
			"HitBox",
			"MonsterInfo",
			"Guidance",
			"GuidanceStep",
			"MonsterDrops",
            "CollectionDrops",
            "DropPerformance",
            "LevelNPC",
            "Story",
            "DialogButton",
            "DialogChain",
            "DialogPrologue",
			"AttributeMatching",
			"MapMechanism",
			"BattleVoice",
			"AchievementType",
			"AchievementRewards",
			"AchievementMedal",
			"IndicatorType",
	        "Suitbox",
			"SuitboxDecompose",
			"SuitboxCoin",
			"PassportReward",
			"PassportTask",
			"PassportShow",
			"WeaponShow",
			"Teaching",
			"TeachingBook",
			"HeroTeachingConfig",
			"LevelTeachingConfig",
			"HeroTeachingInfo",
			"TeachingTask",
			"TimeTask",
			"GameExplain",
			"Packs",
			"PacksInclude",
			"TimeLimit",
			
			
			//抽卡
			"DrawCardInfo",
			"RareUp",
			"Choose",
			"CardByProduct",
			
			//家园
			"HomeLandShopGoodsGroup",
			"BuildingInfo",
			"HomeLandLevelInfo",
			"HomeLandLevelEffect",
			"BuildingLevelInfo",
			"FarmLevel",
			"FarmSeed",
			"SailEventQualityRate",
			"SailEvent",
			"SailLightLevel",
			
			//公会
			"GuildLev",
			"GuildJobInfo",
			"GuildActiveReward",
			"GuildActiveTask",
			"GuildConfig",
			"GuildBuff",
			"GuildEvent",
#if UNITY_EDITOR || (!FORMALPROCESS && !BUSINESS_PACKAGE)
	        "CostomCultivate",
#endif
	        //游戏手册
	        "GameGuideView",
	        "CollectionNote",
	        "TimeLineNote",
	        "BranchTimeLineNote",
	        "CGNote",
	        "MonsterNote",
	        "MonsterSkillNote",
	        "MapNote",
	        "SceneryNote",
	        "NPCNote",
	        "HeroNote",
	        "HeroTag",
	        "HeroDetails",
	        "HeroStory",
	        "HeroTreasure",
	        "HeroCG",
	        
	        "Decompose",
	        "WholeApart",
	        "Manual",
	        "HeroGuide",
	        
	        "ActiveTask",
	        "ActiveReward",
	        "Money",
	        
	        "Banner",
	        "BankGroup"
        };

        
        /// <summary>
        /// 最小精度变量
        /// </summary>
        public const double TOLERANCE = 0.001f;
        
        /// <summary>
        /// 默认逻辑帧时间
        /// </summary>
        public const float INITINTERVALTIMER = 0.033f;
    }
}